# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

env:
  LOG_LEVEL: "debug"
  POSTGRES_ADDRESS: "postgres://admin:admin@localhost:5432/orders?sslmode=disable"

tasks:
  run:
    cmds:
      - go run -v main.go

  docker-network:
    cmds:
      - docker network create cloud-native-network 2>/dev/null || true

  docker-build:
    cmds:
      - docker build -t cloud-native-api:latest .

  docker-run:
    deps:
      - docker-network
      - docker-build
    cmds:
      - |
        docker rm -f cloud-native-api 2>/dev/null || true

        docker run \
          --name cloud-native-api \
          --network cloud-native-network \
          --env-file .env \
          -p 8080:8080 \
          cloud-native-api:latest

  dev-psql-container:
    deps:
      - docker-network
    cmds:
      - |
        docker rm -f orders-db 2>/dev/null || true

        docker volume create orders-db-data >/dev/null

        docker run \
          --name orders-db \
          --network cloud-native-network \
          -p 5432:5432 \
          -e POSTGRES_USER=admin \
          -e POSTGRES_PASSWORD=admin \
          -e POSTGRES_DB=orders \
          -v orders-db-data:/var/lib/postgresql/data \
          -d postgres:17

        echo "Waiting for PostgreSQL..."

        until docker exec orders-db pg_isready -U admin -d orders; do
          sleep 1
        done

        echo "PostgreSQL is ready"

        goose up-to 20260831194800
    env:
      GOOSE_DRIVER: "postgres"
      GOOSE_DBSTRING: "postgres://admin:admin@localhost:5432/orders?sslmode=disable"
      GOOSE_MIGRATION_DIR: ./schema
      GOOSE_TABLE: "goose_db_version"

  cleanup-psql-container:
    cmds:
      - goose down
    env:
      GOOSE_DRIVER: "postgres"
      GOOSE_DBSTRING: "postgres://admin:admin@localhost:5432/orders?sslmode=disable"
      GOOSE_MIGRATION_DIR: ./schema
      GOOSE_TABLE: "goose_db_version"