name: Build application

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Download dependencies"
        run: |

      - name: "Run tests check"
        run: |